[package]
name = "iwtsr"
version = "0.1.0"
edition = "2024"

[lib]
name = "f_hhh"
path = "src/lib.rs"

[dependencies]
gauss-quad = "0.2.4"
thiserror = "2.0"
tracing = "0.1"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
